tasks for pulling and loading calendars
sul-dlss-deprecated/folio-migration-tasks pull request #155
Opened 2023-02-01 21:25 UTC by jgreben

Waiting to load Nolana on folio-test to try this out. Seemingly much simpler than the old model. No schema to test agains (yet?) When I try it out I will perhaps write some kind of test...

2023-03-15 23:54 UTC, jgreben commented
See https://folio-stage.stanford.edu/settings/calendar/all/

2023-03-16 17:23 UTC, shelleydoljack requested changes

2023-03-16 17:23 UTC, shelleydoljack commented on Rakefile
> +                            tenant:pull_calendars]
We should add load_calendars to the load_tenant_settings group task.

2023-03-16 17:58 UTC, shelleydoljack approved these changes

2023-03-16 17:59 UTC, merged