Nolana folio stage
sul-dlss-deprecated/folio-migration-tasks pull request #184
Opened 2023-03-17 22:17 UTC by jgreben

2023-03-17 22:42 UTC, shelleydoljack commented
> Tests are failing with `link_po_lines_to_inventory`. There were new json/acquisition/orders files that were pulled and then uploaded as new fixtures. They are all failing with:
> 
> ```
> JSON::ParserError:
>         783: unexpected token at ''
> ```

There was json data pulled into `json/acquisitions/orders`? Do we have a rake task that pulls that data? That can't be the reason these are failing, something else must be going on. I'll look into it Monday.

2023-03-20 17:57 UTC, shelleydoljack approved these changes
Do you want to wait until QA of stage is done before merging?

2023-03-20 22:15 UTC, jgreben commented
@shelleydoljack do you want to review the last three commits and then we can merge before it gets way too big?

2023-03-21 16:35 UTC, shelleydoljack requested changes

2023-03-21 16:35 UTC, shelleydoljack commented on spec/configurations/load_config_entries_task_spec.rb
>    end
There is [a method that updates the host](https://github.com/sul-dlss/folio-tasks/blob/2b7784dbd1a9569d1ace6102313d2e27f7d924f7/tasks/helpers/configurations.rb#L47-L51) to what is in the value `Settings.namespace` this test was testing. We should either add this test to https://github.com/sul-dlss/folio-tasks/blob/f7a49394220601621cc1621e9892bcfd8a79fea1/spec/configurations/load_email_config_task_spec.rb#L6-L24 or update this test somehow.

2023-03-21 16:35 UTC, shelleydoljack commented on Rakefile
>  desc 'Load all configurations [BULKEDIT CHECKOUT FAST_ADD INVOICE ORDERS ORG SMTP_SERVER TENANT USERSBL]'
Remove SMTP_SERVER from description and add LOAN_HISTORY (and whatever else is added to the config/settings file).

2023-03-21 16:48 UTC, shelleydoljack requested changes

2023-03-21 16:48 UTC, shelleydoljack commented on spec/fixtures/json/inventory/copycat_profiles.json
> +{"profiles":[{"id":"f26df83c-aa25-40b6-876e-96852c3d4fd4","name":"OCLC WorldCat","url":"zcat.oclc.org/OLUCWorldCat","authentication":"100-471-188 / sulmkt19","externalIdQueryMap":"@attr 1=1211 $ident
I don't think we should be checking in the authentication information.

2023-03-21 16:48 UTC, shelleydoljack commented on tasks/helpers/inventory.rb
> +  end
We should maybe add a method that removes the authentication keys from the files saved in the spec/fixtures folder. authentication is not a required field so it shouldn't fail the schema validation.

2023-03-21 21:50 UTC, shelleydoljack requested changes
Sorry, still needs a change...

2023-03-21 21:50 UTC, shelleydoljack commented on spec/configurations/load_email_config_task_spec.rb
> +    end
The value of namespace in config/settings/test.yml is `test` so this test should be failing.

2023-03-21 21:50 UTC, shelleydoljack commented on spec/configurations/load_email_config_task_spec.rb
> +    end
I see the method to update the host is in the post, so probably need to rewrite the test to check what was requested, such as https://github.com/sul-dlss/folio-tasks/blob/f7d1e360fcff4766b59459bb178a1a1e66a6b073/config/settings/test.yml#L18 . Or something like was is exemplified at https://github.com/bblimke/webmock#setting-expectations-in-rspec-on-webmock-module .

2023-03-21 21:54 UTC, jgreben commented on spec/configurations/load_email_config_task_spec.rb
> +    end
Why should that test be failing?
```
 Failure/Error: expect(email_config_json['host'].to_s).to eq 'mail.folio-foo.svc.cluster.local'
     
       expected: "mail.folio-foo.svc.cluster.local"
            got: "mail.folio-test.svc.cluster.local"
```

2023-03-21 22:01 UTC, shelleydoljack commented on spec/configurations/load_email_config_task_spec.rb
> +    end
the [email_config_post method](https://github.com/sul-dlss/folio-tasks/blob/f7d1e360fcff4766b59459bb178a1a1e66a6b073/tasks/helpers/configurations.rb#L80-L83) replaces `hash['value'] = "mail.#{Settings.namespace}.svc.cluster.local"`. I don't think this is working right.

2023-03-21 22:02 UTC, jgreben commented on spec/configurations/load_email_config_task_spec.rb
> +    end
OK I see what's happening...

2023-03-21 22:02 UTC, shelleydoljack commented on spec/configurations/load_email_config_task_spec.rb
> +    end
indeed, the value of "host" for `/smtp-configuration` at folio-stage is "mail.folio-test.svc.cluster.local".

2023-03-21 22:20 UTC, jgreben commented on spec/configurations/load_email_config_task_spec.rb
> +    end
I changed the method that reads in the json from the file to set the host according to the namespace.

2023-03-21 22:35 UTC, shelleydoljack approved these changes
Everything else looks good.

2023-03-21 22:35 UTC, shelleydoljack commented on tasks/helpers/configurations.rb
> +    hash
Ok. It'll work for test, stage, and prod (if our settings file is correct) but not dev... not sure if we want to remove the 'folio-' part or not. The previous way was `"mail.#{Settings.namespace}.svc.cluster.local"`

2023-03-21 22:39 UTC, jgreben commented on tasks/helpers/configurations.rb
> +    hash
I changed it back, realizing that..

2023-03-21 22:41 UTC, jgreben commented on tasks/helpers/configurations.rb
> +    hash
It would be better if we could just use ENV['STAGE'] for that instead of the settings, but we would have the same problem with dev. Maybe we should get ops to change the namespace ¯\_(ツ)_/¯

2023-03-22 15:38 UTC, shelleydoljack commented on tasks/helpers/configurations.rb
> +    hash
At this point, I think we don't need to worry about it not working in dev for either solution (ENV or settings)... we're not using that namespace to test emails anyways.

2023-03-22 16:43 UTC, merged