Fix Harvester
sul-dlss-deprecated/folio-migration-tasks pull request #263
Opened 2023-08-29 04:24 UTC by jgreben

2023-08-30 21:02 UTC, shelleydoljack requested changes

2023-08-30 21:02 UTC, shelleydoljack commented on run/harvest.env
> +HARVEST_HOME=$(ruby -ryaml -e "puts YAML::load_file(\"$(dirname $0)/../config/settings/$STAGE.yml\")['harvester_home']")
I think it'd be better to set an absolute path for the config/settings dir and call it here. Does that not work?

2023-08-30 22:11 UTC, jgreben commented on run/harvest.env
> +HARVEST_HOME=$(ruby -ryaml -e "puts YAML::load_file(\"$(dirname $0)/../config/settings/$STAGE.yml\")['harvester_home']")
It's then just one more place to remember to set the application path.

2023-08-30 22:12 UTC, jgreben commented on run/harvest.env
> +HARVEST_HOME=$(ruby -ryaml -e "puts YAML::load_file(\"$(dirname $0)/../config/settings/$STAGE.yml\")['harvester_home']")
There are already 2 places to set the path. In the settings and in the processor.properties file.

2023-08-31 16:15 UTC, shelleydoljack commented on run/harvest.env
> +HARVEST_HOME=$(ruby -ryaml -e "puts YAML::load_file(\"$(dirname $0)/../config/settings/$STAGE.yml\")['harvester_home']")
ok

2023-08-31 16:16 UTC, shelleydoljack commented
Something is still not quite right. The emails for the load, errors, and deactivate users were empty. I see this in the log for last night's run:
```

2023-08-31 17:08 UTC, jgreben commented on run/do-person-harvest.sh
> +if [[ -n $3 ]]; then
This is what was preventing the harvest from running. The date was not being set and and the harvest xml file was coming out as `harvest.xml.out.`

2023-08-31 18:12 UTC, shelleydoljack approved these changes

2023-09-06 16:51 UTC, shelleydoljack approved these changes

2023-09-06 16:51 UTC, merged