Rakes tasks for working with data import profiles
sul-dlss-deprecated/folio-migration-tasks pull request #289
Opened 2024-02-08 21:03 UTC by shelleydoljack

Closes #288

2024-02-08 23:24 UTC, jgreben requested changes
Do we still need this method? If not, it can be removed: https://github.com/sul-dlss/folio-tasks/blob/6ec600cb10514b9cb14ed0cbe2dc926d0a3b07b6/tasks/helpers/data_import.rb#L217

2024-02-09 18:06 UTC, shelleydoljack commented
On second thought, I might want to use that method instead. Let me re-work this PR a bit.

2024-02-13 18:21 UTC, shelleydoljack commented
> Do we still need this method? If not, it can be removed:
> 
> https://github.com/sul-dlss/folio-tasks/blob/6ec600cb10514b9cb14ed0cbe2dc926d0a3b07b6/tasks/helpers/data_import.rb#L217

I ended up removing it. This is ready for review now.

2024-02-13 18:27 UTC, jgreben approved these changes

2024-02-13 18:27 UTC, merged