Refactor acq units to avoid repeated top level variable warning
sul-dlss-deprecated/folio-migration-tasks pull request #66
Opened 2022-07-26 15:54 UTC by jgreben

When `@@folio_request` is instantiated in a `.rake` file it repeatedly warns about the use of a top-level variable assignment, and while using this `@@` assignment is not the most elegant solution to the problem of repeated folio logins, it's the best I could come up with given our project structure. Moving the instantiation to a ruby module at leasts  minimizes the warnings.

2022-07-27 16:36 UTC, shelleydoljack requested changes

2022-07-27 16:36 UTC, shelleydoljack commented on tasks/helpers/acq_units.rb
> +  end
Maybe use the method in the [AcquisitionsUuidsHelpers](https://github.com/sul-dlss/folio-tasks/blob/245ce0a63850b51576c0fbbe948b5db1f3970939/tasks/helpers/uuids/acquisitions.rb#L9-L15).

2022-07-27 16:36 UTC, shelleydoljack commented on tasks/helpers/acq_units.rb
> +  end
Consider moving this method to the [AcquisitionsUuidsHelpers](https://github.com/sul-dlss/folio-tasks/blob/main/tasks/helpers/uuids/acquisitions.rb).

2022-08-26 21:11 UTC, jgreben reviewed
LGTM

2022-08-26 21:11 UTC, merged